language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-head
script: "bundle exec rake spec"
